# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/rsrc.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_rsrc(object):
    def setupUi(self, rsrc):
        rsrc.setObjectName("rsrc")
        rsrc.resize(777, 600)
        self.centralwidget = QtWidgets.QWidget(rsrc)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2.addLayout(self.gridLayout, 0, 2, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.processing = QtWidgets.QWidget()
        self.processing.setObjectName("processing")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.processing)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.scrollArea = QtWidgets.QScrollArea(self.processing)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 735, 479))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.swapbox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.swapbox.setMinimumSize(QtCore.QSize(200, 200))
        self.swapbox.setObjectName("swapbox")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.swapbox)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.swap = QtWidgets.QGridLayout()
        self.swap.setObjectName("swap")
        self.gridLayout_8.addLayout(self.swap, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.swapbox, 1, 0, 1, 1)
        self.rambox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.rambox.setMinimumSize(QtCore.QSize(200, 200))
        self.rambox.setObjectName("rambox")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.rambox)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.ram = QtWidgets.QGridLayout()
        self.ram.setObjectName("ram")
        self.gridLayout_10.addLayout(self.ram, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.rambox, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.cpubox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.cpubox.setMinimumSize(QtCore.QSize(200, 200))
        self.cpubox.setObjectName("cpubox")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.cpubox)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.cpu = QtWidgets.QGridLayout()
        self.cpu.setObjectName("cpu")
        self.gridLayout_9.addLayout(self.cpu, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.cpubox, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_7.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.tabWidget.addTab(self.processing, "")
        self.processes = QtWidgets.QWidget()
        self.processes.setObjectName("processes")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.processes)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.tabWidget_4 = QtWidgets.QTabWidget(self.processes)
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.all = QtWidgets.QWidget()
        self.all.setObjectName("all")
        self.gridLayout_45 = QtWidgets.QGridLayout(self.all)
        self.gridLayout_45.setObjectName("gridLayout_45")
        self.gridLayout_44 = QtWidgets.QGridLayout()
        self.gridLayout_44.setObjectName("gridLayout_44")
        self.deselect_all = QtWidgets.QPushButton(self.all)
        self.deselect_all.setObjectName("deselect_all")
        self.gridLayout_44.addWidget(self.deselect_all, 1, 0, 1, 1)
        self.tasks = QtWidgets.QTableView(self.all)
        self.tasks.setObjectName("tasks")
        self.gridLayout_44.addWidget(self.tasks, 0, 0, 1, 1)
        self.gridLayout_45.addLayout(self.gridLayout_44, 0, 0, 1, 1)
        self.tabWidget_4.addTab(self.all, "")
        self.gridLayout_16.addWidget(self.tabWidget_4, 0, 0, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_16, 0, 0, 1, 1)
        self.tabWidget.addTab(self.processes, "")
        self.disk = QtWidgets.QWidget()
        self.disk.setObjectName("disk")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.disk)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.gridLayout_24 = QtWidgets.QGridLayout()
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.disk)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.info = QtWidgets.QWidget()
        self.info.setObjectName("info")
        self.gridLayout_33 = QtWidgets.QGridLayout(self.info)
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.gridLayout_32 = QtWidgets.QGridLayout()
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.gridLayout_33.addLayout(self.gridLayout_32, 0, 0, 1, 1)
        self.tabWidget_3.addTab(self.info, "")
        self.monitor = QtWidgets.QWidget()
        self.monitor.setObjectName("monitor")
        self.gridLayout_31 = QtWidgets.QGridLayout(self.monitor)
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.gridLayout_30 = QtWidgets.QGridLayout()
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.gridLayout_31.addLayout(self.gridLayout_30, 0, 0, 1, 1)
        self.tabWidget_3.addTab(self.monitor, "")
        self.gridLayout_24.addWidget(self.tabWidget_3, 0, 0, 1, 1)
        self.gridLayout_25.addLayout(self.gridLayout_24, 0, 0, 1, 1)
        self.tabWidget.addTab(self.disk, "")
        self.network = QtWidgets.QWidget()
        self.network.setObjectName("network")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.network)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.gridLayout_22 = QtWidgets.QGridLayout()
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.network)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.info1 = QtWidgets.QWidget()
        self.info1.setObjectName("info1")
        self.gridLayout_29 = QtWidgets.QGridLayout(self.info1)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.gridLayout_28 = QtWidgets.QGridLayout()
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.gridLayout_29.addLayout(self.gridLayout_28, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.info1, "")
        self.monitor1 = QtWidgets.QWidget()
        self.monitor1.setObjectName("monitor1")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.monitor1)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.network_monitor = QtWidgets.QGridLayout()
        self.network_monitor.setObjectName("network_monitor")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.monitor1)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 709, 426))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_38 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_38.setObjectName("gridLayout_38")
        self.net = QtWidgets.QGridLayout()
        self.net.setObjectName("net")
        self.gridLayout_38.addLayout(self.net, 0, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.network_monitor.addWidget(self.scrollArea_2, 0, 0, 1, 1)
        self.gridLayout_27.addLayout(self.network_monitor, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.monitor1, "")
        self.gridLayout_22.addWidget(self.tabWidget_2, 0, 0, 1, 1)
        self.gridLayout_23.addLayout(self.gridLayout_22, 0, 0, 1, 1)
        self.tabWidget.addTab(self.network, "")
        self.battery = QtWidgets.QWidget()
        self.battery.setObjectName("battery")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.battery)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.battery_tabs = QtWidgets.QTabWidget(self.battery)
        self.battery_tabs.setObjectName("battery_tabs")
        self.info2 = QtWidgets.QWidget()
        self.info2.setObjectName("info2")
        self.gridLayout_35 = QtWidgets.QGridLayout(self.info2)
        self.gridLayout_35.setObjectName("gridLayout_35")
        self.gridLayout_34 = QtWidgets.QGridLayout()
        self.gridLayout_34.setObjectName("gridLayout_34")
        self.gridLayout_35.addLayout(self.gridLayout_34, 0, 0, 1, 1)
        self.battery_tabs.addTab(self.info2, "")
        self.monitor2 = QtWidgets.QWidget()
        self.monitor2.setObjectName("monitor2")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.monitor2)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.gridLayout_18 = QtWidgets.QGridLayout()
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.gridLayout_19.addLayout(self.gridLayout_18, 0, 0, 1, 1)
        self.battery_tabs.addTab(self.monitor2, "")
        self.gridLayout_12.addWidget(self.battery_tabs, 0, 0, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_12, 0, 0, 1, 1)
        self.tabWidget.addTab(self.battery, "")
        self.sensors = QtWidgets.QWidget()
        self.sensors.setObjectName("sensors")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.sensors)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.sensors_tabs = QtWidgets.QTabWidget(self.sensors)
        self.sensors_tabs.setObjectName("sensors_tabs")
        self.info3 = QtWidgets.QWidget()
        self.info3.setObjectName("info3")
        self.gridLayout_37 = QtWidgets.QGridLayout(self.info3)
        self.gridLayout_37.setObjectName("gridLayout_37")
        self.gridLayout_36 = QtWidgets.QGridLayout()
        self.gridLayout_36.setObjectName("gridLayout_36")
        self.gridLayout_37.addLayout(self.gridLayout_36, 0, 0, 1, 1)
        self.sensors_tabs.addTab(self.info3, "")
        self.monitor3 = QtWidgets.QWidget()
        self.monitor3.setObjectName("monitor3")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.monitor3)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.gridLayout_20 = QtWidgets.QGridLayout()
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.gridLayout_21.addLayout(self.gridLayout_20, 0, 0, 1, 1)
        self.sensors_tabs.addTab(self.monitor3, "")
        self.gridLayout_14.addWidget(self.sensors_tabs, 0, 0, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_14, 0, 0, 1, 1)
        self.tabWidget.addTab(self.sensors, "")
        self.settings = QtWidgets.QWidget()
        self.settings.setObjectName("settings")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.settings)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_4 = QtWidgets.QLabel(self.settings)
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 9, 0, 1, 1)
        self.facecolor = QtWidgets.QLineEdit(self.settings)
        self.facecolor.setMaximumSize(QtCore.QSize(125, 16777215))
        self.facecolor.setObjectName("facecolor")
        self.gridLayout_6.addWidget(self.facecolor, 10, 0, 1, 1)
        self.gridColor = QtWidgets.QLineEdit(self.settings)
        self.gridColor.setMaximumSize(QtCore.QSize(125, 16777215))
        self.gridColor.setObjectName("gridColor")
        self.gridLayout_6.addWidget(self.gridColor, 13, 0, 1, 1)
        self.setLineFmt = QtWidgets.QPushButton(self.settings)
        self.setLineFmt.setObjectName("setLineFmt")
        self.gridLayout_6.addWidget(self.setLineFmt, 8, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.settings)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)
        self.line_fmt = QtWidgets.QComboBox(self.settings)
        self.line_fmt.setObjectName("line_fmt")
        self.gridLayout_6.addWidget(self.line_fmt, 7, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.settings)
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 12, 0, 1, 1)
        self.graphSize = QtWidgets.QSpinBox(self.settings)
        self.graphSize.setMaximum(120)
        self.graphSize.setSingleStep(1)
        self.graphSize.setProperty("value", 25)
        self.graphSize.setObjectName("graphSize")
        self.gridLayout_6.addWidget(self.graphSize, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.settings)
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 3, 0, 1, 1)
        self.interval = QtWidgets.QSpinBox(self.settings)
        self.interval.setMaximum(1000000177)
        self.interval.setSingleStep(100)
        self.interval.setProperty("value", 2000)
        self.interval.setObjectName("interval")
        self.gridLayout_6.addWidget(self.interval, 1, 0, 1, 1)
        self.select_gridColor = QtWidgets.QPushButton(self.settings)
        self.select_gridColor.setObjectName("select_gridColor")
        self.gridLayout_6.addWidget(self.select_gridColor, 14, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.settings)
        self.label_3.setObjectName("label_3")
        self.gridLayout_6.addWidget(self.label_3, 6, 0, 1, 1)
        self.intervalSet = QtWidgets.QPushButton(self.settings)
        self.intervalSet.setObjectName("intervalSet")
        self.gridLayout_6.addWidget(self.intervalSet, 2, 0, 1, 1)
        self.setGraphSize = QtWidgets.QPushButton(self.settings)
        self.setGraphSize.setObjectName("setGraphSize")
        self.gridLayout_6.addWidget(self.setGraphSize, 5, 0, 1, 1)
        self.select_facecolor = QtWidgets.QPushButton(self.settings)
        self.select_facecolor.setObjectName("select_facecolor")
        self.gridLayout_6.addWidget(self.select_facecolor, 11, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem, 2, 1, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.settings, "")
        self.gridLayout_2.addWidget(self.tabWidget, 1, 2, 1, 1)
        rsrc.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(rsrc)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 777, 22))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        rsrc.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(rsrc)
        self.statusbar.setObjectName("statusbar")
        rsrc.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(rsrc)
        self.actionQuit.setObjectName("actionQuit")
        self.menu_File.addAction(self.actionQuit)
        self.menubar.addAction(self.menu_File.menuAction())

        self.retranslateUi(rsrc)
        self.tabWidget.setCurrentIndex(3)
        self.tabWidget_4.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(1)
        self.battery_tabs.setCurrentIndex(0)
        self.sensors_tabs.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(rsrc)

    def retranslateUi(self, rsrc):
        _translate = QtCore.QCoreApplication.translate
        rsrc.setWindowTitle(_translate("rsrc", "Hydrogenous Resource Monitor"))
        self.swapbox.setTitle(_translate("rsrc", "Swap"))
        self.rambox.setTitle(_translate("rsrc", "Memory"))
        self.cpubox.setTitle(_translate("rsrc", "CPU"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.processing), _translate("rsrc", "Processing"))
        self.deselect_all.setText(_translate("rsrc", "Deselect"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.all), _translate("rsrc", "All"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.processes), _translate("rsrc", "Processes"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.info), _translate("rsrc", "Info."))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.monitor), _translate("rsrc", "Monitor"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.disk), _translate("rsrc", "Disk"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.info1), _translate("rsrc", "Info."))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.monitor1), _translate("rsrc", "Monitor"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.network), _translate("rsrc", "Network"))
        self.battery_tabs.setTabText(self.battery_tabs.indexOf(self.info2), _translate("rsrc", "Info."))
        self.battery_tabs.setTabText(self.battery_tabs.indexOf(self.monitor2), _translate("rsrc", "Monitor"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.battery), _translate("rsrc", "Battery"))
        self.sensors_tabs.setTabText(self.sensors_tabs.indexOf(self.info3), _translate("rsrc", "Info."))
        self.sensors_tabs.setTabText(self.sensors_tabs.indexOf(self.monitor3), _translate("rsrc", "Monitor"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sensors), _translate("rsrc", "Sensors"))
        self.label_4.setText(_translate("rsrc", "Background Color"))
        self.setLineFmt.setText(_translate("rsrc", "Set"))
        self.label.setText(_translate("rsrc", "Interval"))
        self.label_5.setText(_translate("rsrc", "Grid Color"))
        self.label_2.setText(_translate("rsrc", "Graph Size"))
        self.select_gridColor.setText(_translate("rsrc", "Select"))
        self.label_3.setText(_translate("rsrc", "Line Formats"))
        self.intervalSet.setText(_translate("rsrc", "Set"))
        self.setGraphSize.setText(_translate("rsrc", "Set"))
        self.select_facecolor.setText(_translate("rsrc", "Select"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settings), _translate("rsrc", "Settings"))
        self.menu_File.setTitle(_translate("rsrc", "&File"))
        self.actionQuit.setText(_translate("rsrc", "&Quit"))
        self.actionQuit.setShortcut(_translate("rsrc", "Ctrl+Q"))


